FROM node:18-slim

WORKDIR /app

COPY package*.json ./
COPY servanza-services/workers/package*.json ./servanza-services/workers/
COPY .npmrc ./

RUN npm install --legacy-peer-deps

COPY . .

WORKDIR /app/servanza-services/workers
RUN npm run prisma:generate || true
RUN npm run build --if-present || true

CMD ["npm", "run", "dev"]
